version: '3.7'

services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: inception-nginx
    networks:
      - app-net
    ports:
      - "80:80"
      - "443:443"
networks:
  app-net:
