version: '3.7'

services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: inception-nginx
    restart: unless-stopped
    networks:
      - inception-net
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mariadb
      - wordpress
    volumes:
      - wp-data:/var/www/html:ro

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: inception-wordpress
    restart: unless-stopped
    networks:
      - inception-net
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_HOST: mariadb:3306
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USERNAME: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER_USERNAME: ${WP_USER_USERNAME}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
    volumes:
      - wp-data:/var/www/html:rw


  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: inception-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - inception-net
    volumes:
      - db-data:/var/lib/mysql:rw

networks:
  inception-net:

volumes:
  db-data: {}
  wp-data: {}
